language: node_js
node_js:
- '6'
- '5'
- '4'
- '0.12'
- '0.11'
- '0.10'
- iojs-v1
- iojs-v2
- iojs-v3
script: npm install --only=dev;npm test
branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^release\/.*$/
